#!/bin/sh
# Based on https://github.com/coreos/etcd/blob/master/build

GOSHIP_PACKAGE=github.com/gengo/goship
export GOPATH="${PWD}"
SRC_DIR="$GOPATH/src"
GOSHIP_DIR="$SRC_DIR/$GOSHIP_PACKAGE"
GOSHIP_BASE=$(dirname "${GOSHIP_DIR}")
if [ ! -d "${GOSHIP_BASE}" ]; then
        mkdir -p "${GOSHIP_BASE}"
fi

if [ ! -h "${GOSHIP_DIR}" ]; then
        ln -s ../../../ "${GOSHIP_DIR}"
fi

for i in third_party/*; do
        if [ "$i" = "third_party/src" ]; then
                continue
        fi
        cp -R "$i" src/
done

echo $GOPATH
go build "${GOSHIP_PACKAGE}"
